trigger:
  branches:
    include:
      - master
variables:
  - template: variables/build.yml

pool:
  vmImage: '$(buildImage)'

steps:
  - task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
    inputs:
      channel: 'stable'
      version: '$(flutterVersion)'

  - script: flutter pub get
    displayName: 'Install dependencies'

  - script: flutter test
    displayName: 'Run Dart & Flutter tests'

  - script: flutter build apk --release
    displayName: 'Build Android APK'

  - script: flutter build ios --release --no-codesign
    displayName: 'Build iOS IPA (unsigned)'

  - task: CopyFiles@2
    inputs:
      contents: |
        $(androidArtifactPath)
        $(iosArtifactPath)
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Collect build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'flutter-builds'
      publishLocation: 'Container'
    displayName: 'Publish artifacts for download'
