trigger:
  branches:
    include:
      - master
variables:
  - template: variables/build.yml

pool:
  vmImage: '$(buildImage)'

steps:
  - script: |
      git clone https://github.com/flutter/flutter.git -b stable
      echo "##vso[task.setvariable variable=PATH]$(Build.SourcesDirectory)/flutter/bin:$PATH"
    displayName: 'Install Flutter SDK manually'

  - script: flutter doctor
    displayName: 'Verify Flutter installation'

  - script: flutter --version
    displayName: 'Check Flutter version'

  - script: flutter pub get
    workingDirectory: 'expense_tracker_flutter_app'
    displayName: 'Install dependencies'

  - script: flutter test
    workingDirectory: 'expense_tracker_flutter_app'
    displayName: 'Run Dart & Flutter tests'

  - script: flutter build apk --release
    workingDirectory: 'expense_tracker_flutter_app'
    displayName: 'Build Android APK'

  - script: flutter build ios --release --no-codesign
    workingDirectory: 'expense_tracker_flutter_app'
    displayName: 'Build iOS IPA (unsigned)'

  - task: CopyFiles@2
    workingDirectory: 'expense_tracker_flutter_app'
    inputs:
      contents: |
        $(androidArtifactPath)
        $(iosArtifactPath)
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Collect build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'flutter-builds'
      publishLocation: 'Container'
    displayName: 'Publish artifacts for download'
